### ISSUE TITLE
Allow multiple gene sets for GSEA

### ISSUE THREAD

**Issue by grst** [nf-core/differentialabundance#102]
### Description of feature

Currently it is possible to specify a single `gmt` file for gene signatures. I would find it useful if it was possible to specify multiple sets of gene signatures (e.g. KEGG, HALLMARK, GO biological process, GO molecular functions, and that these manually curated gene sets I got from the collaborator). 

They should also appear as separate tables in the MultiQC report.

**Comment by pinin4fjords** [comment]
Sounds good- PRs gratefully received.
