### ISSUE TITLE
input samplesheet template for affimetrix data

### ISSUE THREAD

**Issue by dansteiert** [nf-core/differentialabundance#118]
### Description of feature

As I am not sure how to write the samplesheet for affimetrix data, could you supply a template as done for the RNAseq

I guess it would be something along these lines:
what I dont know yet:
 - is there a specified column name for cel_files?
 - is it just the name of the files as they are present in the tar file
 
 
sample,cel_file,condition,replicate,batch
CONTROL_REP1,AEG588A1_S1_L002_R1_001.CEL,control,1,A
CONTROL_REP2,AEG588A1_S1_L003_R1_001.CEL,control,2,B
CONTROL_REP3,AEG588A1_S1_L004_R1_001.CEL,control,3,A
TREATED_REP1,AEG588A2_S1_L002_R1_001.CEL,treated,1,B
TREATED_REP2,AEG588A2_S1_L003_R1_001.CEL,treated,2,A
TREATED_REP3,AEG588A2_S1_L004_R1_001.CEL,treated,3,B

**Comment by pinin4fjords** [comment]
I'll try to add some documentation to make that clearer before the next release. In the meantime, take a look at how the affy files from the test_affy profile look, that should get you started https://github.com/nf-core/differentialabundance/blob/master/conf/test_affy.config.

**Comment by pinin4fjords** [comment]
I should say that the sample sheet in the assets is a hangover from workflow creation that should be removed , it's not actually a useful starting point for anything.

**Comment by dansteiert** [comment]
Thank you! - that is what I have been looking for.
More specific, the file listed in the config for the sample file
https://raw.githubusercontent.com/nf-core/test-datasets/differentialabundance/testdata/GSE50790.csv

**Comment by dansteiert** [comment]
> I should say that the sample sheet in the assets is a hangover from workflow creation that should be removed , it's not actually a useful starting point for anything.

This is rather a comment for future development than for me/users right?

**Comment by pinin4fjords** [comment]
I just didn't want you to use it as a basis for anything- the test profiles are better place to look
