### ISSUE TITLE
Proxy-Setting/Prevent R from Internet Search

### ISSUE THREAD

**Issue by dansteiert** [nf-core/differentialabundance#120]
### Description of feature

Hi differentialabundance Team,

I tried running the pipeline, and got an error, that R/Bioconductor is trying to retrieve/verify packages, accompanied by a  "Couldn't conncet to server", which I assume is due to my proxy settings.

 I am using the singularity profile.
 Is there an option to set my proxy or prevent R from searching the interenet in the first place?
 
 Below is my error message:
 
```
Error executing process > 'NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:AFFY_JUSTRMA_RAW (study)'

Caused by:
  Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:AFFY_JUSTRMA_RAW (study)` terminated with an error exit status (1)
```

The full R script ...

```
Command exit status:
  1

Command output:
  (empty)

Command error:
  Loading required package: BiocGenerics

  Attaching package: ‘BiocGenerics’

  The following objects are masked from ‘package:stats’:

      IQR, mad, sd, var, xtabs

  The following objects are masked from ‘package:base’:

      anyDuplicated, aperm, append, as.data.frame, basename, cbind,
      colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
      get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
      match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
      Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
      table, tapply, union, unique, unsplit, which.max, which.min

  Loading required package: Biobase
  Welcome to Bioconductor

      Vignettes contain introductory material; view with
      'browseVignettes()'. To cite Bioconductor, see
      'citation("Biobase")', and for packages 'citation("pkgname")'.

  Error: Bioconductor version cannot be validated; no internet connection?  See
    #troubleshooting section in vignette
  In addition: Warning messages:
  1: In file(con, "r") :
    URL 'https://bioconductor.org/config.yaml': status was 'Couldn't connect to server'
  2: In file(con, "r") :
    URL 'http://bioconductor.org/config.yaml': status was 'Couldn't connect to server'
  Execution halted

```

**Comment by dansteiert** [comment]
Thank you anyway for having a look into it!

I was hoping there is some nextflow config, where I can pass all my proxy information into, such that each container can access the interenet if there is a need for it, but apparently this is not the case, right?

**Comment by SPPearce** [comment]
If you (as the user) build a singularity container with the required packages then you could override the `container` directive for that process locally via a config. The script might need updating to check if the package already exists before trying to download it though.

Alternatively there could be an optional file location which could be staged into the progress to be checked in case the file exists before going to the internet.
