### ISSUE TITLE
workaround OPENBLAS using all cores problem

### ISSUE THREAD

**Issue by colindaven** [nf-core/differentialabundance#135]
### Description of feature

There is a well known problem where DESeq2 uses too many cores, eg all 40 on the machine, instead of the desired 4 for example. This is a problem in this pipeline where I am running jobs on the local server, not the cluster. It may not be apparent when running on a cluster, since the cgroups implementation should restrict OPENBLAS to eg 4 cores, even though the library would otherwise use 40.

OS: Ubuntu 2004

Workaround - use your own nextflow.config, eg in the current directory where you are running nextflow from (which should take precedence over configs from the workflow itself).

Just add this snippet to your `nextflow.config` in the current directory.
```

env {
     // restrict DESeq2 to less than all cores
     OPENBLAS_NUM_THREADS='4'
}
```

Hope that helps, now Deseq2 R jobs are using 4 cores, not trying to all use 40 and overloading the server.

Colin

**Comment by pinin4fjords** [comment]
Hi @colindaven - thanks for the contribution. Could I persuade you to PR this to the 'hints and tips' of the documentation? https://github.com/nf-core/differentialabundance/blob/master/docs/usage.md#hints-and-tips.
