### ISSUE TITLE
Add log2_assays docu to nextflow_schema after shiny fix

### ISSUE THREAD

**Issue by WackerO** [nf-core/differentialabundance#153]
### Description of feature

Plot_exploratory currently does not accept `--log2_assays [assay1,assay2]` because of a missing call to prettify so I omitted the respective line from nextflow_schema.config; when that is fixed, add
`list of assay names enclosed by square brackets, e.g. '[raw,normalised]'; or list`

**Comment by pinin4fjords** [comment]
Could you expand on what you mean by 'a missing call to prettify' @WackerO? What needs to change?

**Comment by WackerO** [comment]
Ah that is not a problem anymore, solved by dealing with the [] in modules.config instead of in the R code. Will add this to the nextflow_schema in my next PR I think

**Comment by WackerO** [comment]
To follow up, it _was_ still an issue, but this is solved whenever the next shinyngs release and update is done.

**Comment by grst** [comment]
The 2.0 release of shiny ngs was in July this year... can this be closed?

**Comment by pinin4fjords** [comment]
yep, let's assume so
