### ISSUE TITLE
Add module(s) for proteomics analysis

### ISSUE THREAD

**Issue by WackerO** [nf-core/differentialabundance#17]
### Description of feature

I will start looking into some Px functionality for differentialabundance

**Comment by pinin4fjords** [comment]
Was just looking at https://nf-co.re/quantms, and wondering if maybe this is actually better taken care of there? Uses https://www.bioconductor.org/packages/release/bioc/html/MSstats.html

**Comment by WackerO** [comment]
I am working on some modules to analyze maxquant output, and I believe quantms does not deal with such files so I would think adding this to diffab is useful. I am going to check though if quantms does after all have maxquant functionality

**Comment by WackerO** [comment]
#147 closes this
