### ISSUE TITLE
Sample metadata table in the html report is not paginating

### ISSUE THREAD

**Issue by davidecarlson** [nf-core/differentialabundance#191]
### Description of the bug

The sample metadata table only lists 10 rows at a time and is supposed to spill over into additional clickable pages if there are more than 10 samples.  Currently, this not occurring.  The link to click on the next set of samples does not appear below the table.

@pinin4fjords determined that this can be fixed by change `dom = 't'` to `dom = 'tp'` in [the report template here](https://github.com/nf-core/differentialabundance/blob/44c449be0a703c64a7c323a2b431ec6627194f00/assets/differentialabundance_report.Rmd#L429).  I've confirmed that this solves the issue.

I will submit a PR with this change soon and am opening this issue so that I can reference it in the changelog.

Best,
Dave

**Comment by davidecarlson** [comment]
I just wanted to reopen this issue. It was resolved previously, but it seems like the fix didn't actually make it into the 1.5.0 release, even though it's noted in the changelog.

The [file in question](https://github.com/nf-core/differentialabundance/blob/44c449be0a703c64a7c323a2b431ec6627194f00/assets/differentialabundance_report.Rmd#L429) seems to be fixed on the dev branch, so maybe there is nothing else that needs to be done, but it's not fixed in the Master branch despite what the release notes say, so I wanted to bring it up anyway.

**Comment by pinin4fjords** [comment]
Actually dev and master are [the same](https://github.com/nf-core/differentialabundance/blob/master/assets/differentialabundance_report.Rmd#L490), it's just that there was a typo in the fix ('tb' rather than 'tp'). 

I'll apply another fix. Note that you can supply your own amended template via `--report_file` before such time as this make it into a release.
