### ISSUE TITLE
Gene set analysis 

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/differentialabundance#21]
### Description of feature

Probably a basic part of any differential analysis (particularly in expression) is a gene set analysis. I propose we have a module for the Broad's GSEA if it's feasible.

Module-level issue https://github.com/nf-core/modules/issues/2584.

**Comment by pinin4fjords** [comment]
Adding GSEA to Bioconda at https://github.com/bioconda/bioconda-recipes/pull/38167 (was a bit a surprised it wasn't there already, but there you go).

**Comment by apeltzer** [comment]
One could also think about:

* GSVA
* PLAGE
* SingScore

**Comment by pinin4fjords** [comment]
> One could also think about:
> 
> * GSVA
> * PLAGE
> * SingScore

@apeltzer Absolutely - could I persuade you to create issues for each? GSEA will suffice for the MVP I think, and will establish the interface we can hopefully repurpose for the others.

**Comment by apeltzer** [comment]
See #24 , #25, #26

**Comment by pinin4fjords** [comment]
GSEA module now merged from https://github.com/nf-core/modules/pull/2617

Two additional adapter modules added to generate the correct [matrix](https://github.com/nf-core/modules/pull/2603) and [class file](https://github.com/nf-core/modules/pull/2606) formats.

**Comment by pinin4fjords** [comment]
TODO: integration work for this workflow
