### ISSUE TITLE
Final report, volcano plot: points wrongly marked red 

### ISSUE THREAD

**Issue by mtruglio** [nf-core/differentialabundance#212]
### Description of the bug

In the plotly volcano plot, genes should be red if 

`padj<=0.05 and abs(log2FC)>=2 
`

as per the legend, but actually the report marks as red all the genes that have 

`padj<=0.05 and abs(log2FC)>=**1**
`

This is also evident in the [example report](https://nf-co.re/differentialabundance/1.4.0/results/differentialabundance/results-a3d664c12c4050bae2acc83b1c636dcc3546b9a5/report/?file=study.html), in the volcano plot for "_KO versus WT in Condition genotype (blocking: batch)_", genes _pof1b_ or _dsg2_ for example.

So either the legend for the red dot should be changed, or there is a conditional to fix somewhere during report generation.

Thanks

**Comment by pinin4fjords** [comment]
Thanks for the report- just an oversight in the legend.
