### ISSUE TITLE
Mark --matrix as a required parameter in the parameter section on the diffabundance website

### ISSUE THREAD

**Issue by aghr** [nf-core/differentialabundance#238]
### Description of feature

If the parameter --matrix is required and I believe it is then please add the tag 'required' to it so that users quickly see which parameters they need to set at minimum.

**Comment by WackerO** [comment]
Hey there, the --matrix parameter is actually not required. For the geo_soft_file study_type option, you don't need to input a matrix but rather a GEO identifier.

**Comment by grst** [comment]
Closing as this has been answered.
