### ISSUE TITLE
Remove parameter --gsea_run

### ISSUE THREAD

**Issue by aghr** [nf-core/differentialabundance#239]
### Description of feature

For running a GSEA I would invoke min these two parameters  --gsea_gene_sets XXXX --gsea_run true. To reduce the number of parameters it could make sense to remove --gsea_run true and run the GSEA if the user provides gene sets via  --gsea_gene_set XXXX.

**Comment by WackerO** [comment]
Hey @aghr,
as mentioned in https://github.com/nf-core/differentialabundance/issues/243, there is now also gprofiler which shares the gene set param but can be run independently, so it is necessary to have the gsea_run param to enable running either of the two enrichment tools (or none) even when providing a file.
I'm closing this issue, feel free to reopen if you have any more input regarding this.
