### ISSUE TITLE
volcano plot cannot be edited in the report

### ISSUE THREAD

**Issue by jml96** [nf-core/differentialabundance#287]
### Description of the bug

I would like to change the log2FoldChange cutoff in the volcano plot. I set --differential_min_fold_change to log2(0.5) with different precisions and I always get 0.50000003838469 or 0.499999936370744. I tried to edit chart with plotly but I got a message "Could not recognize data as Plotly JSON for a plot or grid(s). For help, please search Plotly's [community forum](http://community.plotly.com/).". I can open other charts in the report.
Any suggestion to resolve this issue?
Thank you.

**Comment by WackerO** [comment]
Hello @jml96, I just tried setting the parameters to 0.5 and it worked perfectly for me...If you can share your dataset and params, I could try to reproduce the bug with it?

**Comment by jml96** [comment]
Hi,
I rerun the nf-core/differentialabundance pipeline on my data and this time I was able to edit the volcano plot a remove the excessive number of digits.
Thank you for your help.

From: WackerO ***@***.***>
Date: Wednesday, 11 September 2024 at 08:06
To: nf-core/differentialabundance ***@***.***>
Cc: jml96 ***@***.***>, Mention ***@***.***>
Subject: Re: [nf-core/differentialabundance] volcano plot cannot be edited in the report (Issue #287)

Hello @jml96<https://github.com/jml96>, I just tried setting the parameters to 0.5 and it worked perfectly for me...If you can share your dataset and params, I could try to reproduce the bug with it?

**Comment by WackerO** [comment]
Glad to hear it!
