### ISSUE TITLE
 Command error:   gtf2featureAnnotation.R: command not found   ---pipeline test

### ISSUE THREAD

**Issue by cloud2266** [nf-core/differentialabundance#291]
Hi, I am trying to run the pipeline and encountered the problem with "....gtf2featureAnnotation.R: command not found" repeatedly, even when I specifically export the  R:  export PATH=/.../.../../R/4.3.2/bin:$PATH, the exact same issue persists.

I started to use the test to check the run:  "nextflow run nf-core/differentialabundance -r 1.5.0 -profile test --outdir test_pipeline"
Again, I run into the exact same error (see below).     Could someone help and shed some light on this issue ? 

Thank you very much !

"....................
Caused by:
  Process `NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GTF_TO_TABLE (Mus_musculus)` terminated with an error exit status (127)
.....................
cat <<-END_VERSIONS > versions.yml
  "NFCORE_DIFFERENTIALABUNDANCE:DIFFERENTIALABUNDANCE:GTF_TO_TABLE":
      atlas-gene-annotation-manipulation: 1.1.1
  END_VERSIONS
Command exit status:
  127
Command output:
  (empty)
Command error:
  .command.sh: line 3: gtf2featureAnnotation.R: command not found  "

**Comment by WackerO** [comment]
Hey there, is there any chance you could run the pipeline with one of the container options? Singularity, docker, etc.? Or even conda? Those would get rid of such issues.

Otherwise, did you try if you can call the gtf2featureAnnotation.R directly in the command line? If not, then something did not work when you exported it to PATH.

**Comment by cloud2266** [comment]
Thank you very much, I truly appreciate the help.

I did try "-profile singularity" and encountered the exact same issue. I am running this on a cluster.

With your suggestion, I tested the following:
$ gtf2featureAnnotation.R  --gtf-file /gpfs/data/nixonlab/janet/reference/GRCm39.111_tran/Mus_musculus.GRCm39.111.gtf  --output-file Mus_musculus.anno.tsv  --feature-type 'transcript' --first-field 'gene_id'

I got the same error:  Command error:
.command.sh: line 3: gtf2featureAnnotation.R: command not found "

When I mannually added Rscript, it worked!   
$ Rscript gtf2featureAnnotation.R  --gtf-file /gpfs/data/nixonlab/janet/reference/GRCm39.111_tran/Mus_musculus.GRCm39.111.gtf  --output-file Mus_musculus.anno.tsv  --feature-type 'transcript' --first-field 'gene_id'

But when running the pipeline via singularity profile, how could I add the "Rscript"  command?  Thanks again for helping !

**Comment by WackerO** [comment]
I'm sorry, I don't think I understand what you are trying to do.
Why did you run this command?
 `$ gtf2featureAnnotation.R --gtf-file /gpfs/data/nixonlab/janet/reference/GRCm39.111_tran/Mus_musculus.GRCm39.111.gtf --output-file Mus_musculus.anno.tsv --feature-type 'transcript' --first-field 'gene_id'`

This is supposed to be done automatically by the pipeline (as in, when you run the command `nextflow run nf-core/differentialabundance blabla...`, the gtf2featureAnnotation script will be called internally by the pipeline), so you should not need to type this command manually?

**Comment by cloud2266** [comment]
Thanks again! much appreciated!   -- That is the problem:  the pipeline consistently crashed at that step both with local run " -- profile singularity" and test run "--profile test".

With your suggestion " did you try if you can call the gtf2featureAnnotation.R directly in the command line?", I copied the failed command lines from file .nextflow.log, and run directly on the command line.  The results shared previously appear to suggest that "Rscript" command is required to get it work; without "Rscript", the "gtf2featureAnnotation.R" alone returns "command not found", in my computing environment right now.

Thanks again for commenting, suggestions, helping, thanks.

**Comment by WackerO** [comment]
Aha interesting; I thought the gtf2featureAnnotation.R script should be executable directly...

Glad it worked now, I'll close this issue then :)

**Comment by cloud2266** [comment]
Thank you very much for your help. I was out of office for sometime, and did not check email.

I wonder if it would be possible for you to add "Rscript" in front of "gtf2featureAnnotation.R",  I checked with my HPC supporting staff whether something I could do to execute "gtf2featureAnnotation.R", and was told that I need to add Rscript myself.

It doesn't seem that others have the same issue, I am guessing that this is computing environment dependent.   Thanks again for considering this.

Best
