### ISSUE TITLE
https://nf-co.re/differentialabundance/1.5.0/docs/usage/#g should be the full name:gprofiler2, not just g

### ISSUE THREAD

**Issue by vmkalbskopf** [nf-core/differentialabundance#305]
### Description of the bug

The "section title" for the gprofiler2 section on [https://nf-co.re/differentialabundance/1.5.0/docs/usage](https://nf-co.re/differentialabundance/1.5.0/docs/usage) is just "g", and it should be "gprofiler2".

### Relevant files

![Image](https://github.com/user-attachments/assets/11ac4840-b650-41e5-b7fe-f267f633aa72)

**Comment by WackerO** [comment]
This is now fixed on dev
