### ISSUE TITLE
add test data

### ISSUE THREAD

**Issue by suzannejin** [nf-core/differentialabundance#321]
current mus musculus test data don't provide significant propd/propr coefficients
- [ ] add additional test data

**Comment by nschcolnicov** [comment]
Hi @suzannejin I'm looking into adding this additional test profile, but I'm having a hard time understanding where are you looking at these propr/propd coefficients in the report generated. Do you have an example on what are you expecting to see?

For example, looking at the example report hosted in nf-core:
https://nf-co.re/differentialabundance/1.5.0/results/differentialabundance/results-3dd360fed0dca1780db1bdf5dce85e5258fa2253/report/?file=study.html

I can't see which are the plots or tables that are displaying these coefficients

**Comment by suzannejin** [comment]
hello @nschcolnicov sorry for the late reply! 
The thing is that I am trying to add a new DE method into the pipeline. However when testing that new method, when I use a more conservative statistical test like permutation test, etc, no DE genes are found -> so empty output and it does not make sense to test on such output.
So, I think that having more than one available test dataset (ie. mus musculus) in nf-core would be beneficial for more extensive testing of modules/pipelines.

**Comment by nschcolnicov** [comment]
Hi @suzannejin, I see, would it be possible to share the branch where you are working on these changes? I can blindly add a bigger dataset, but I think it would be better to run it within the same workflow you are testing, this way I can make sure it actually outputs some DE genes.

**Comment by suzannejin** [comment]
@nschcolnicov I need to finish some tests on the module itself... maybe I can ask you for a review when i add the data I am trying now?

**Comment by suzannejin** [comment]
hello @nschcolnicov at the end I did not need an extra data for it. Thanks a lot though for offering the help :)
I am gonna close the issue with this
