### ISSUE TITLE
add module DESEQ2

### ISSUE THREAD

**Issue by suzannejin** [nf-core/differentialabundance#322]
- [ ] add module DESEQ2 into the experimental branch

**Comment by LucilleAugusta** [comment]
Hi @suzannejin, 

I would like to work on this issue. 
Is the experimental branch created - or should I create one from dev? 

Br, 
Lucille

**Comment by suzannejin** [comment]
hello @LucilleAugusta 

Thank you for joining!
We have a branch called `dev-ratio`, to which you should PR your changes.

You could see from this branch that we are trying to reorganize the structure of the pipeline into a more modular one.
So that `differentialabundance.nf` calls --> `subworkflow/experimental.nf`
And from this experimental.nf it calls to the subsequence analysis wrapped into subworkflows, basically:
1) subworkflow/differential
2) subworkflow/correlation
3) subworkflow/enrichment

You could add the DESEQ2 module into subworkflow/differential.nf

NOTE: as you may see, it is half added, in the sense we added at some point the call to DESEQ2, but then we updated the rest of the code, so it is not properly working. You would need to properly handled the input channels and call DESEQ2
