### ISSUE TITLE
Assess if we should simplify CUSTOM_TABULARTO GSEACLS

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/differentialabundance#355]
### Description of feature

Current version is a combination of bash commands, it could be worth to update it into python or R so that it is easier to read and review by anyone.
As discussed in https://github.com/nf-core/differentialabundance/issues/249#issuecomment-2462134567 and https://github.com/nf-core/differentialabundance/issues/249#issuecomment-2476431213.

@grst @pinin4fjords

**Comment by grst** [comment]
Frankly, if the current version works, I don't see a reason to change it. 
I just thought if it needs to be fixed, it could be easier to rewrite in a more readable language.

**Comment by pinin4fjords** [comment]
Yep, if it ain't broke don't fix it.
