### ISSUE TITLE
Create nf-tests for local module filter_difftable.nf

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/differentialabundance#379]
### Description of feature

Create nf-tests for local module filter_difftable.nf and update folder structure for nf-core standards

**Comment by nschcolnicov** [comment]
Hi @pinin4fjords while I was creating tests for this local module, I saw that you generated an nf-core version of it. Can I go ahead and introduce it to the pipeline replacing the local module? https://github.com/nf-core/modules/tree/b6515a01897b11b64b3368858c0359b4c813ad1e/modules/nf-core/custom/filterdifferentialtable

**Comment by pinin4fjords** [comment]
Oh, yep, sure @nschcolnicov . I did it to support https://github.com/nf-core/modules/pull/7115, which is puzzling me right now, and would have done it at the same time, but no harm in you doing it now.
