### ISSUE TITLE
Implement nf-test

### ISSUE THREAD

**Issue by WackerO** [nf-core/differentialabundance#61]
### Description of feature

I'm going to switch the github ci to pytest-workflow so that github can monitor the consistency of pipeline output instead of just checking that PRs don't make the pipeline fail

**Comment by apeltzer** [comment]
Rather go for nf-test please, not pytest anymore.

**Comment by WackerO** [comment]
I will move this back a bit until the hackathon, maybe nf-test can be discussed then (if this is the recommended nf-core/nextflow testing tool, it would be great to also have a bit more documentation, e.g. how to best test multiple profiles of a pipeline)

**Comment by grst** [comment]
PR is open here: https://github.com/nf-core/differentialabundance/pull/168

**Comment by pinin4fjords** [comment]
> PR is open here: [#168](https://github.com/nf-core/differentialabundance/pull/168)

I've just closed it. I think we can do better now. There's a standard pattern emerging now- see the rnaseq example: https://github.com/nf-core/rnaseq/blob/master/tests/default.nf.test

**Comment by atrigila** [comment]
I was working exactly on that pattern :), will send PR soon

**Comment by atrigila** [comment]
Closed via #343
