### ISSUE TITLE
Color palette includes hard to read bright yellow

### ISSUE THREAD

**Issue by Shellfishgene** [nf-core/differentialabundance#68]
### Description of the bug

The color palette used for plots includes yellow which is hard to see on white background, e.g. in pca2d. Maybe only an issue with many conditions.

![grafik](https://user-images.githubusercontent.com/1769465/218160967-813b28c0-7318-4159-9589-b1ef9861f0c6.png)

**Comment by pinin4fjords** [comment]
Upstream fix allowing palette name specification completed in https://github.com/pinin4fjords/shinyngs/pull/35 and released in shinyngs version 1.5.6.

**Comment by pinin4fjords** [comment]
Modules bump https://github.com/nf-core/modules/pull/2893
