### ISSUE TITLE
Establish outputs/ reports

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/differentialabundance#8]
### Description of feature

I'm unsure on the detail of how to implement this due to lack of nf-core experience, but we'll need to set up the final reporting (ideally visible in Tower), presenting the results of the differential analysis in an interpretable way. 

MultiQC integration?

**Comment by nicholas-owen** [comment]
Would this be something akin to an RMarkdown report that summarizes the MultiQC output, alignment stats,  creates the DESeq2 object, and produces transformations, PCA plots, Eigen plots, MA/Volcano and tables of DEGs ? Apologies it not, am getting into the nf-core experience as well.

**Comment by pinin4fjords** [comment]
So alignment stats etc belong in the upstream workflows I think (for now at least, maybe we can think about combining somehow later). 

We already have separate modules for running the DESeq analysis, and for making some of the plots.

It's the compilation of the differential abundance tables (TSVs etc) and plots (pngs or htmls) into something coherent we need to figure out, initially it may just be dumping them into the final location, but that's not all that nice.
