### ISSUE TITLE
Allow use of different primary feature identifier in outputs

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/differentialabundance#84]
### Description of feature

It is sometimes useful to use a different primary feature identifier in output files than the one from the input matrix. We should allow that conversion to happen as part of processing.

I imagine this being a simple local module that remaps matrix identifiers early on in the workflow by referencing the feature annotation table.

**Comment by grst** [comment]
Common use case: Use ensemble identifier as unique primary identifier, but still show gene symbols in plots, and use Gene sets based on gene symbols.

**Comment by pinin4fjords** [comment]
> Common use case: Use ensemble identifier as unique primary identifier, but still show gene symbols in plots, and use Gene sets based on gene symbols.

Actually I think that use case should be served by maintaining both ids and symbols, and converting to symbols close to where you need to plot. The pipeline has a parameter for the name field for exactly this reason. Symbols in particular are not good primary identifiers- they are not unique, and are missing on a number of genes. 

I don't actually remember the use case I had in mind when I wrote this...

**Comment by grst** [comment]
Ok, then it sounds like it's already covered. Shall we close the issue then?

**Comment by pinin4fjords** [comment]
As I say, I think I had something different in mind when I wrote this. More a case of mapping actual identifiers (rather than names). But I don't remember why, so we may as well close until I remember.
